title:  Blog
description: Disconnetus Erectus
author: Nuri Çilengir
github: https://github.com/derectus
about: Security Researcher at Prodaft
disqus_shortname: nurilengir-me
google_analytics: UA-164493833-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/der3ctus"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/cilengirnuri/"
    - icon: fa-reddit
      link: "https://www.reddit.com/user/erectustd"
    - icon: fa-github
      link: "https://github.com/derectus"

share:
  twitter_username: der3ctus

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "http://nurilengir.me/"
baseurl: ""
paginate: 25
per_page: 25
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
